excluded:
  - RizeDesktop.xcodeproj
  - .build
  - DerivedData
  - build

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - redundant_nil_coalescing
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

disabled_rules:
  - todo

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500
